services:
  - type: web
    name: fastfood-signal
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 3000
    plan: free
